### ISSUE TITLE
Extensibility via DLLs

### ISSUE THREAD

**Issue by sr229** [ProjectLovewing/Charter#1]
To be able to provide extensibility, we can look at having `.dll`s for specific features:

- Beatmap support
- Editor extensions (let's say, a advanced keyframer)

We can do the following in-tree for plugins but we'll need to document to people how to make it

## TODO

- [ ] Extension API (we can do this as a `.csproj` per in-tree plugin to test this)
- [ ] In-tree Plugins 
       - [ ] Bandori Support - `Charter.Beatmap.Bandori`
       - [ ] Lovewing Support  - `Charter.Beatmap.Lovewing`
       - [ ] LiveSim 2 support -  `Charter.Beatmap.AuahDark` 
- [ ] Documentation

**Comment by MikuAuahDark** [comment]
> LiveSim 2 support - `Charter.Beatmap.AuahDark`

Why it must be `AuahDark` tho. `Charter.Beatmap.Livesim2` is enough, no need to use my name for it lol.
